"""
PDF Component - Generates PDF reports for country data.
"""
import os
from typing import List
from fpdf import FPDF

# Get the directory where this script is located

from datetime import datetime
from .constants import BASE_DIR, APP_NAME, APP_VERSION, CREATORS

class CountryPDF(FPDF):
    """Custom PDF class for detailed country reports."""
    
    def header(self):
        if self.page_no() > 1:  # No header on cover page
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 10, f"{APP_NAME} v{APP_VERSION} - Country Report", align="R")
            self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


    def create_cover_page(self, total_countries):
        self.add_page()
        
        # Logo / Branding
        logo_path = os.path.join(BASE_DIR, "logo.png")
        if os.path.exists(logo_path):
            img_width = 150  # Increased from 50
            x_centered = (self.w - img_width) / 2
            self.image(logo_path, x=x_centered, y=30, w=img_width)
            self.ln(95) # Moves cursor down (y=30 + width=80 approx)
        else:
            self.ln(60)
            
        self.set_font("Helvetica", "B", 24) # Reduced from 30
        self.cell(0, 20, APP_NAME.upper(), align="C", ln=True)
        
        self.set_font("Helvetica", "", 10) # Reduced from 12
        self.cell(0, 10, f"Version {APP_VERSION}", align="C", ln=True)
        
        self.ln(20)
        self.set_font("Helvetica", "B", 18) # Reduced from 24
        self.cell(0, 20, "Comprehensive Country Data Report", align="C", ln=True)
        
        self.ln(10)
        self.set_font("Helvetica", "I", 11) # Reduced from 14
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C", ln=True)
        
        self.ln(40)
        self.set_font("Helvetica", "", 10) # Reduced from 12
        self.cell(0, 10, "Created by:", align="C", ln=True)
        self.set_font("Helvetica", "B", 12) # Reduced from 14
        for creator in CREATORS:
            self.cell(0, 8, creator, align="C", ln=True)

    def create_intro_section(self, total_countries):
        self.add_page()
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "1. Executive Summary", ln=True)
        self.ln(5)
        
        self.set_font("Helvetica", "", 11)
        text = (
            f"This document serves as a comprehensive report generated by the {APP_NAME}. "
            f"It currently maintains a database of {total_countries} countries from around the world.\n\n"
            "The data presented includes international standards such as ISO codes, "
            "financial information (currencies), communication details (phone prefixes), "
            "and cultural data (spoken languages).\n\n"
            "This report is generated automatically based on the latest available data "
            "in the system registry."
        )
        self.multi_cell(0, 6, text)
        self.ln(20)

    def create_data_table(self, countries):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "2. Country Registry", ln=True)
        self.ln(5)
        
        # Table Header
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(240, 240, 240)
        
        # Adjusted widths for 7 columns
        col_widths = [12, 12, 45, 20, 25, 20, 50]
        headers = ["ISO", "ISO3", "Country", "Currency", "Phone", "TLD", "Languages"]
        
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 8, header, border=1, align="C", fill=True)
        self.ln()
        
        # Table Content
        self.set_font("Helvetica", "", 8)
        for country in countries:
             # Check for page break
            if self.get_y() > 270:
                self.add_page()
                # Re-print header
                self.set_font("Helvetica", "B", 9)
                self.set_fill_color(240, 240, 240)
                for i, header in enumerate(headers):
                    self.cell(col_widths[i], 8, header, border=1, align="C", fill=True)
                self.ln()
                self.set_font("Helvetica", "", 8)

            self.cell(col_widths[0], 7, str(country.get("iso", "")), border=1, align="C")
            self.cell(col_widths[1], 7, str(country.get("iso3", "")), border=1, align="C")
            
            # Truncate to fit
            name = str(country.get("country", ""))[:23]
            self.cell(col_widths[2], 7, name, border=1)
            
            self.cell(col_widths[3], 7, str(country.get("currency_code", "")), border=1, align="C")
            self.cell(col_widths[4], 7, str(country.get("phone", "")), border=1, align="C")
            self.cell(col_widths[5], 7, str(country.get("tld", "")), border=1, align="C")
            
            langs = str(country.get("languages", ""))[:30]
            self.cell(col_widths[6], 7, langs, border=1)
            self.ln()


def generate_pdf(countries: List[dict], filename: str = "countries_report.pdf") -> tuple[bool, str]:
    try:
        pdf = CountryPDF()
        
        # 1. Cover Page
        pdf.create_cover_page(len(countries))
        
        # 2. Intro / Explanation
        pdf.create_intro_section(len(countries))
        
        # 3. Data Table
        pdf.create_data_table(countries)
        
        # Save
        output_path = os.path.join(BASE_DIR, filename)
        pdf.output(output_path)
        
        return True, output_path
    
    except Exception as e:
        return False, f"Error generating PDF: {e}"
